# Variables
AS = nasm
ASFLAGS = -f elf64 -g -F dwarf # -g and -F dwarf are for debugging
LD = ld
GCC = gcc
LDFLAGS = -no-pie
OUTDIR = out

# Get all .asm files and define their resulting object names in ./out
SRCS_ASM = $(wildcard *.asm)
SRCS_C = $(wildcard *.c)
SRCS_CPP = $(wildcard *.cpp)

OBJS_ASM = $(patsubst %.asm,$(OUTDIR)/%.o,$(SRCS))
OBJS_C = $(patsubst %.c,$(OUTDIR)/%.o,$(SRCS))
OBJS_CPP = $(patsubst %.cpp,$(OUTDIR)/%.obj,$(SRCS))

APP = app.exe

# Default target: build all
all: $(APP)

# Rule to link object files into an executable
$(APP): $(OBJS)
	$(GCC) $(LDFLAGS) -o $@ $^

# Ensure output directory exists
$(OUTDIR):
	mkdir -p $(OUTDIR)

# Rule to assemble .asm into ./out/*.o
$(OUTDIR)/%.o: %.asm | $(OUTDIR)
	$(AS) $(ASFLAGS) $< -o $@

# Clean up
clean:
	rm -rf $(OUTDIR) $(APP)

.PHONY: all clean